speed_sector_tuner:
  ros__parameters:
    global_limit: 0.48   # 0822: 라인 벽여유 2mm — 재생성 전 보수 운행
    n_sectors: 1
    Sector0:
      start: 0
      end: 409
      scaling: 1.0
      only_FTG: false
      no_FTG: false
