detect:
  ros__parameters:
    rate_detect: 40
    min_size_n: 4
    min_size_m: 0.29999999999999999
    max_size_m: 0.59999999999999998
    lambda_deg: 10
    sigma: 0.029999999999999999
    min_2_points_dist: 0.01
    new_cluster_threshold_m: 0.40000000000000002
    max_viewing_distance: 9
    boundaries_inflation: 0.10000000000000001
    filter_kernel_size: 7
    measure: false
    from_bag: false
    save_params: false
tracking:
  ros__parameters:
    save_params: false
    rate_tracking: 40
    P_vs: 0.2
    P_d: 0.02
    P_vd: 0.2
    measurment_var_s: 0.002
    measurment_var_d: 0.002
    measurment_var_vs: 0.2
    measurment_var_vd: 0.2
    process_var_vs: 2.0
    process_var_vd: 8.0
    max_dist: 0.5
    var_pub: 1.0
    aggro_multi: 2.0
    dist_deletion: 7.0
    dist_infront: 8.0
    max_std: 0.2
    min_std: 0.16
    min_nb_meas: 5
    noMemoryMode: true
    debug_mode: false
    publish_static: true
    ratio_to_glob_path: 0.6
    ttl_dynamic: 40
    ttl_static: 3
    vs_reset: 0.1
    measure: false
    from_bag: false