sector_tuner:
  ros__parameters:
    global_limit: 1.0
    n_sectors: 5
    Sector0:
      start: 0
      end: 39
      scaling: 1.0
      only_FTG: false
      no_FTG: false
    Sector1:
      start: 40
      end: 66
      scaling: 1.0
      only_FTG: false
      no_FTG: false
    Sector2:
      start: 67
      end: 92
      scaling: 1.0
      only_FTG: false
      no_FTG: false
    Sector3:
      start: 93
      end: 121
      scaling: 1.0
      only_FTG: false
      no_FTG: false
    Sector4:
      start: 122
      end: 179
      scaling: 1.0
      only_FTG: false
      no_FTG: false
